### ISSUE TITLE
能否支持一下angular？

### ISSUE THREAD

**Issue by Coder7777** [pansyjs/watermark#95]
好像不支持angular项目？试了一下报错。

core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'append')
TypeError: Cannot read properties of null (reading 'append')
    at Watermark.<anonymous> (index.js:350:23)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:25:24)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25488:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25475:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
    at resolvePromise (zone.js:1213:1) [angular]
    at :8100/polyfills.js:4261:17 [angular]
    at fulfilled (index.js:27:9) [angular]
    at Object.onInvoke (core.mjs:25488:1) [angular]
    at :8100/polyfills.js:4417:36 [angular]
    at Object.onInvokeTask (core.mjs:25475:1) [angular]
    at drainMicroTaskQueue (zone.js:582:1) [<root>]
    at invokeTask (zone.js:491:1) [<root>]

**Comment by wangxingkang** [comment]
暂时不支持的，不是很了解 angular 欢迎PR

**Comment by nzbin** [comment]
Angular 版本在这里
https://github.com/acrodata/watermark
